name: Action

on:
  push:
    branches:
      - main

jobs:
  make_documentation:
    name: make_documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install doxygen
        run: sudo apt-get update; sudo apt-get install -y doxygen
      - name: run doxygen
        run: doxygen doxyfile
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
